### ISSUE TITLE
"group movies into collections" Does not work

### ISSUE THREAD

**Issue by Gra-K** [jellyfin/jellyfin-web#1133]
The option in dashboard to group movies into collections when viewing the movie folder, does not work. 

**To Reproduce**
1. Go to dashboard
2. Click on Libraries
3. Scroll down to 'Group movies into collections'
4. Tick selection
5. Go to movies in my media
6. No movies are displayed as a collection - For example harry potter 1 - 8 are displayed, rather then the harry potter collection folder

**System (please complete the following information):**
 - OS: Docker
 - Browser: Tested on latest stable Firefox and Chrome
 - Jellyfin Version: 10.5.4

**Additional context**

**Comment by MrTimscampi** [comment]
Do you have the `TMDb Box Sets` plugin installed or any custom collections created?

**Comment by Gra-K** [comment]
I don't have any plugins added, and i have 28 custom collections created, which group fine in the dedicated collections tab

**Comment by MrTimscampi** [comment]
Thanks for the additional info, it'll help us to figure this out when we get to this issue.

**Comment by usulpt** [comment]
also happens in Windows build, version 10.5.4

**Comment by Artiume** [comment]
This is now fixed

https://github.com/jellyfin/jellyfin/pull/3117

**Comment by Gra-K** [comment]
I know this has been closed, but just FYI the issue still exists on the nightly docker releases.
