### ISSUE TITLE
BufferFullError when playing with high bitrate

### ISSUE THREAD

**Issue by blackjack4494** [jellyfin/jellyfin-web#1256]
**Describe the bug**
When I try to play 4k or even 1080p content with high bitrate in Chrome the video will stop pretty fast without being able to resume. For 4k this can be as fast as 8 seconds or up to 30 seconds. 1080p got a bit more time.
However if I pick e.g. 1080p 6mbps media will just play fine without any issues.

I have no clue whether there is a buffer limit set in Chrome, jellyfin-web or any of its dependencies.

**To Reproduce**
Use high bitrate media in Chrome.

**Expected behavior**
Play the movie without any problems related to buffer.

**Logs**
See Screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/4406639/82163513-0beb7a80-98ac-11ea-99a6-c264973e7637.png)

**System (please complete the following information):**
 - OS: Windows10 
 - Browser: Chrome
 - Jellyfin Version: (latest) 10.5.5

**Additional context**
https://emby.media/community/index.php?/topic/74257-playback-is-paused-in-the-first-minute-and-cant-be-resumed/
Some emby user having exact same problems.

**Comment by nyanmisaka** [comment]
Also encountered this issue on Chromium based browser. Firefox and Safari logged the error but didn't break playback.

Transcoding HEVC Main10 4K 37.1Mbps to 1080P-60M using NVENC. No errors if I use software encoder.

HLS segments from the hardware encoder are always larger then those from libx264 encoder. It is especially obvious when the target bit rate is high. That might result in reaching the limit of buffer in hls player.

@MrTimscampi Is it feasible to let the player ignore this error and continue playing?

**Comment by MrTimscampi** [comment]
@nyanmisaka I think this was just fixed by an update from HLS.js, but not sure. Can you try to reproduce it on nightly? We might simply backport the update if that fixes it.

**Comment by MrTimscampi** [comment]
Actually, that's a different issue. I'm not sure if we can fix this, it might be down to how the browser implements the HTMLVideoElement.

**Comment by nyanmisaka** [comment]
just build from source and the issue is still here.

![image](https://user-images.githubusercontent.com/14953024/87970134-e706c400-caf5-11ea-9b91-8d8857662998.png)

**Comment by blackjack4494** [comment]
I think it's some limitation by Chrome itself. But there could be a workaround. The web player could implement something that tracks the state of the buffer, when it's near full tell the server to stop sending data or at least slowing it down. When it reaches a lower threshold start sending data again respectively increase the data transfer. It would be interesting to know how other people solved the problem (plex/emby for instance) or whether there is a simpler solution maybe already built in somewhere.

**Comment by Kla3mus** [comment]
I have seen issues registered hos emby with the same issue
Emby: https://emby.media/community/index.php?/topic/74257-playback-is-paused-in-the-first-minute-and-cant-be-resumed/

There is an issue on hls.js with the same issue.
https://github.com/video-dev/hls.js/issues/1084

There's a comment saying that it could be fixed with setting `config.maxBufferLength=20`, I tried this, but were not able to find any success. I might not have done it properly tho.

**Comment by blackjack4494** [comment]
I do indded have an Nvidia card. So I assume Chrome will try to use GPU acceleration by default then? Youtube 4k and even 8k. Would need to check how much data is sent when watching 8k.

**Comment by nyanmisaka** [comment]
try to set `maxMaxBufferLength: 3` at https://github.com/jellyfin/jellyfin-web/blob/7d77cc9900d7adb434f38b4e718dbff0a97688b8/src/plugins/htmlVideoPlayer/plugin.js#L395

**Comment by Kla3mus** [comment]
@nyanmisaka I just tried adding this, with no luck. Unfortunately.

**Comment by nyanmisaka** [comment]
It should like this, and you have to `yarn install` to rebuild the web client.
```
const hls = new Hls({
    maxMaxBufferLength: 3,
    manifestLoadingTimeOut: 20000
});
```

This indeed fixes my issue on Chrome/Edge chromium with NVENC if >= 1080P 30M was chosen.
Streaming 4K in HLS was always interrupted before this.

For reference: https://github.com/video-dev/hls.js/blob/master/docs/API.md#maxmaxbufferlength
```
maxMaxBufferLength
(default 600s)

Maximum buffer length in seconds. Hls.js will never exceed this value, even if maxBufferSize is not reached yet.

hls.js tries to buffer up to a maximum number of bytes (60 MB by default) rather than to buffer up to a maximum nb of seconds. this is to mimic the browser behaviour (the buffer eviction algorithm is starting after the browser detects that video buffer size reaches a limit in bytes)

maxBufferLength is the minimum guaranteed buffer length that hls.js will try to achieve, even if that value exceeds the amount of bytes 60 MB of memory. maxMaxBufferLength acts as a capping value, as if bitrate is really low, you could need more than one hour of buffer to fill 60 MB.
```
