### ISSUE TITLE
Wrong colour for all images

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-web#2179]
**Describe The Bug**
All images are the wrong colour mainly blue

**Steps To Reproduce**

1. Start the server.
2. Look at the home screen

**Expected Behavior**
The images should be the correct colour.

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/56267607/101245108-6fcb7880-3702-11eb-939d-7f9072a10932.png)

**System (please complete the following information):**
 - Platform: Linux, iPhone, Android
 - Browser: Firefox, Safari (and iOS App), Chrome mobile
 - Jellyfin Version: 10.7.0-rc1

**Additional Context**
The colours were correct before the update.

**Comment by TheNamelessWonderer** [comment]
Also the images .local are the correct colour and I have cleared by browser cache.

**Comment by oddstr13** [comment]
Looks like a color channel swap between Red and Blue.

BGR vs RGB

**Comment by TheNamelessWonderer** [comment]
can this be fixed with some CSS? I've asked in the matrix channel and it seems to only be happening to me.

**Comment by TheGreatestJannet** [comment]
I've tried rolling back to 10.6 and upgrading again but the issue still persists.

**Comment by TheNamelessWonderer** [comment]
I have rolled back to 10.6 and tried upgrading again but the issue still persists.

**Comment by oddstr13** [comment]
To debug this, I would suggest having a look at the metadata sources;
Click on the three dots (menu button) on the item in question, then edit images.
![image](https://user-images.githubusercontent.com/638706/101265346-dc1b9b80-3745-11eb-9a59-dadeff61a53e.png)
Click the search button there, and observe what is displayed in the results.


The second place I would suggest you look is in `/var/lib/jellyfin/metadata/library`, find the id of the item from the dashboard, and navigate to it on disk, to see what the image looks like on disk.

This should help narrow down where the issue lies.

**Comment by TheGreatestJannet** [comment]
Images in search are the correct colour and so are the images on the disk. They only appear incorrectly in jellyfin.

**Comment by TheNamelessWonderer** [comment]
Images in search are the correct colour and so are the images on the disk. They only appear incorrectly in Jellyfin.

**Comment by TheNamelessWonderer** [comment]
Also you are correct the Red and Blue channels have been switched over.

**Comment by TheNamelessWonderer** [comment]
I have also completely deleted by library and created a new one and the issue still persists.

**Comment by TheNamelessWonderer** [comment]
I am also running it on macOS Catalina 10.15.7 and native macOS binary. This might be related to the server backend and a library issue on macOS and not related to the web-ui at all.

**Comment by anthonylavado** [comment]
Just tested a "new" library with the 10.6.4 macOS binary and... I'm not getting this issue.

Details:

**Computer**
- macOS Big Sur 11.0.1 (20B29)
- Safari Version 14.0.1 (16610.2.11.51.8)

**iPhone**
- Safari, built-in, iOS 14.2 on iPhone X

**Comment by TheNamelessWonderer** [comment]
It only happens on 10.7. 10.6.4 is fine.

**Comment by anthonylavado** [comment]
I can confirm this issue exists on RC1 of 10.7, with the above mentioned platforms.

**Comment by TheNamelessWonderer** [comment]
Yes! So glad it’s not just me! This looks like a macOS only issue. Do you think it is related to the server backend and should be moved to the other repo?

**Comment by oddstr13** [comment]
According to the system information, am I right in assuming the issue was reproduced by accessing the mac hosted server from Firefox on a linux computer, in addition to the android app?

**Comment by anthonylavado** [comment]
I posit that this issue is caused by a change in platform defaults caused by SkiaSharp, and thus resides in the server's domain. The issue is only presented when an image is modified on demand by the URL requested from the server.

For example, a poster URL in the web interface may look like this:
`http://localhost:8096/Items/e1971882-2dc5-4264-2110-696b3477b43d/Images/Primary?maxHeight=766&maxWidth=510&tag=d39d7f25d88da4dc42bbf98098f477dc&quality=90`

If you remove the modifying query strings:
`http://localhost:8096/Items/e1971882-2dc5-4264-2110-696b3477b43d/Images/Primary?tag=d39d7f25d88da4dc42bbf98098f477dc`
then the image is presented correctly.

As mentioned, it looks like we're victims of an upstream change:
https://github.com/mono/SkiaSharp/issues/1492

**Comment by anthonylavado** [comment]
> According to the system information, am I right in assuming the issue was reproduced by accessing the mac hosted server from Firefox on a linux computer, in addition to the android app?

Running the test server on my iMac, I tried connecting from Windows 10, Firefox 83, and I could see the issue.
