### ISSUE TITLE
Chromium edge direct play HEVC-10bit video and the screen is shaking

### ISSUE THREAD

**Issue by bingzhangdai** [jellyfin/jellyfin-web#2180]
**Describe The Bug**

edge chromium (Version 87.0.664.55 (Official build) (64-bit)) can direct play HEVC-10bit video and Jellyfin does not transcode the video. However the screen is always shaking. I tried many videos and the result is the same.

**Media Information**

```
General
Unique ID                                : 161418311064054559652594287514267689994 (0x7970092FC387D0AAAC051A499E70240A)
Complete name                            : \\omv.moredaisy.local\SATA1\Animations\鬼灭之刃 (2019)\Season 1\鬼灭之刃 - S01E01 - 残酷.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 2.14 GiB
Duration                                 : 23 min 41 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 12.9 Mb/s
Encoded date                             : UTC 2020-06-17 09:09:44
Writing application                      : mkvmerge v32.0.0 ('Astral Progressions') 64-bit
Writing library                          : libebml v1.3.7 + libmatroska v1.5.0

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L4@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 23 min 41 s
Bit rate                                 : 11.3 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 0)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.227
Stream size                              : 1.87 GiB (87%)
Writing library                          : x265 3.3+3-g8f8e332f1+29:[Windows][GCC 9.3.0][64 bit] Yuuki 10bit+8bit+12bit
Encoding settings                        : rc=crf / crf=15.0000 / qcomp=0.65 / qpstep=4 / stats-write=0 / stats-read=0 / vbv-maxrate=30000 / vbv-bufsize=40000 / vbv-init=0.9 / crf-max=0.0 / crf-min=0.0 / no-lossless / no-cu-lossless / aq-mode=1 / aq-strength=0.80 / cbqpoffs=-2 / crqpoffs=-2 / ipratio=1.40 / pbratio=1.20 / psy-rd=1.70 / psy-rdoq=0.80 / deblock=-1:-1 / ref=5 / limit-refs=1 / limit-modes / bframes=8 / b-adapt=2 / bframe-bias=0 / b-pyramid / b-intra / weightp / weightb / min-keyint=1 / max-keyint=360 / rc-lookahead=80 / gop-lookahead=0 / scenecut=40 / hist-scenecut=0 / radl=0 / max-cu-size=32 / min-cu-size=8 / me=3 / subme=4 / merange=57 / rdoq-level=1 / rd=5 / rdpenalty=0 / dynamic-rd=0.00 / no-rd-refine / ----- / cutree / no-sao / rect / no-amp / no-open-gop / wpp / no-pmode / no-pme / no-psnr / no-ssim / nr-intra=0 / nr-inter=0 / no-constrained-intra / no-strong-intra-smoothing / max-tu-size=32 / tu-inter-depth=3 / tu-intra-depth=3 / limit-tu=4 / qg-size=8 / qpmax=69 / qpmin=0 / ----- / cpuid=1111039 / frame-threads=4 / numa-pools=+ / log-level=2 / input-csp=1 / input-res=1920x1080 / interlace=0 / level-idc=0 / high-tier=1 / uhd-bd=0 / no-allow-non-conformance / no-repeat-headers / no-aud / no-hrd / info / hash=0 / no-temporal-layers / lookahead-slices=0 / no-splice / no-intra-refresh / no-ssim-rd / signhide / no-tskip / max-merge=4 / temporal-mvp / no-frame-dup / no-hme / no-analyze-src-pics / no-sao-non-deblock / selective-sao=0 / no-early-skip / rskip / no-fast-intra / no-tskip-fast / no-splitrd-skip / zone-count=0 / no-strict-cbr / no-rc-grain / no-const-vbv / sar=0 / overscan=0 / videoformat=5 / range=0 / colorprim=1 / transfer=1 / colormatrix=1 / chromaloc=1 / chromaloc-top=0 / chromaloc-bottom=0 / display-window=0 / cll=0,0 / min-luma=0 / max-luma=1023 / log2-max-poc-lsb=8 / vui-timing-info / vui-hrd-info / slices=1 / no-opt-qp-pps / no-opt-ref-list-length-pps / no-multi-pass-opt-rps / scenecut-bias=0.05 / hist-threshold=0.01 / no-opt-cu-delta-qp / no-aq-motion / no-hdr10 / no-hdr10-opt / no-dhdr10-opt / no-idr-recovery-sei / analysis-reuse-level=0 / analysis-save-reuse-level=0 / analysis-load-reuse-level=0 / scale-factor=0 / refine-intra=0 / refine-inter=0 / refine-mv=1 / refine-ctu-distortion=0 / no-limit-sao / ctu-info=0 / no-lowpass-dct / refine-analysis-type=0 / copy-pic=1 / max-ausize-factor=1.0 / no-dynamic-refine / no-single-sei / no-hevc-aq / no-svt / no-field / qp-adaptation-range=1.00 / no-scenecut-aware-qpconformance-window-offsets / right=0 / bottom=0
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 2
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 23 min 41 s
Bit rate mode                            : Variable
Bit rate                                 : 1 438 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 11.719 FPS (4096 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 244 MiB (11%)
Writing library                          : libFLAC 1.3.2 (UTC 2017-01-01)
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 23 min 41 s
Bit rate                                 : 179 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 30.2 MiB (1%)
Language                                 : Japanese
Default                                  : No
Forced                                   : No

```
**Screenshots**

![image](https://user-images.githubusercontent.com/9895061/101245429-daeb6e00-3747-11eb-8e3a-fb63ed092754.png)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Edge Version 87.0.664.55 (Official build) (64-bit)
 - Jellyfin Version: 10.6.4

**Additional Context**
I can remember, several months ago, the media can play very well. I am not sure whether it is the regression of Jellyfin or Edge. There is no error in logs.

**Comment by nyanmisaka** [comment]
I also encountered this issue recently in edge chromium 87, but I think this should be an upstream issue in chromium or the hevc plugin from microsoft since this happens in Jellyfin direct play and my nextcloud video player.

**Comment by nyanmisaka** [comment]
I have filed a ticket to Edge community.
https://techcommunity.microsoft.com/t5/discussions/hevc-main-10-video-playback-is-heavily-stuttering/m-p/1959752

**Comment by bingzhangdai** [comment]
Great! I will follow the issue there. Since it is not the problem of Jellyfin, I will close the issue. Thanks for your help.

**Comment by nyanmisaka** [comment]
Seems that the latest [`
HEVC Video Extensions from Device Manufacturer`](https://www.microsoft.com/store/productId/9N4WGH0Z6VHQ) is broken on AMD and NVIDIA.

I have just purchased [`HEVC Video Extensions`](https://www.microsoft.com/store/productId/9NMZLZ57R3T7) and the stutter is gone.

**Comment by bingzhangdai** [comment]
I also purchased the extension. After installing, I experienced a very strange thing, that Jellyfin start transcoding for HEVC.
![image](https://user-images.githubusercontent.com/9895061/101978653-7ec9a200-3c91-11eb-9872-bd79e8779f62.png)

Uninstalling the extension does not turn Edge into direct play. It is very strange. Cloud you @nyanmisaka verify that your Edge is directly playing the video normally?

**Comment by nyanmisaka** [comment]
Can you restart edge to load the new codec?
![image](https://user-images.githubusercontent.com/14953024/101978754-46769380-3c92-11eb-90b1-4724615d5409.png)

**Comment by bingzhangdai** [comment]
Sadly, restarting Edge does not help. I will try to find another PC to recurrent the issue. Maybe it only happens on my laptop. :(

**Comment by nyanmisaka** [comment]
I recall that I also restarted the system due to some updates.

**Comment by nyanmisaka** [comment]
Unfortunately, the issue is back now on edge 87.0.664.66 :/

**Comment by bingzhangdai** [comment]
Same here. I upgraded to the latest stable version 88.0.705.53. The video is now directly playing but becomes shuttering again :(

Nowadays, Microsoft software quality goes down rapidly :(

**Comment by nyanmisaka** [comment]
Seems that Edge team have found the issue. The lastest HEVC plugin is incompatible with Edge. You can downgrade the plugin to 1.0.31823 for the time being. https://www.free-codecs.com/hevc_video_extension_download.htm

![image](https://user-images.githubusercontent.com/14953024/106110559-d8c0f100-6185-11eb-8d09-83278cd69b76.png)

**Comment by kuacci** [comment]
I got this issue with the latest edge and jellyfin recently. But I disabled hardware acceleration in edge then everything goes right now.

![image](https://user-images.githubusercontent.com/5857515/113194227-7b374680-9293-11eb-83d4-a822804e967d.png)

**Comment by kuacci** [comment]
Then we have to wait chromium or edge to improve this. 

Thanks for your sharing, I will test Firefox tonight.

-k

**Comment by bingzhangdai** [comment]
Actually, Firefox does not support HEVC transcoding. Server is responsible for transcoding, hence there is no problem. I use Firefox only because I do not want to change edge default settings.😂

**Comment by wolonggl** [comment]
Can you provide version HEVC Video Extension 1.0.31823 for download? thanks

**Comment by nyanmisaka** [comment]
Remove the .zip suffix before installing it.
[Microsoft.HEVCVideoExtension_1.0.31823.0_x64__8wekyb3d8bbwe.Appx.zip](https://github.com/jellyfin/jellyfin-web/files/6356918/Microsoft.HEVCVideoExtension_1.0.31823.0_x64__8wekyb3d8bbwe.Appx.zip)

**Comment by wolonggl** [comment]
> Remove the .zip suffix before installing it.
> [Microsoft.HEVCVideoExtension_1.0.31823.0_x64__8wekyb3d8bbwe.Appx.zip](https://github.com/jellyfin/jellyfin-web/files/6356918/Microsoft.HEVCVideoExtension_1.0.31823.0_x64__8wekyb3d8bbwe.Appx.zip)

thanks.

**Comment by zjgcjy** [comment]
> Remove the .zip suffix before installing it.
> [Microsoft.HEVCVideoExtension_1.0.31823.0_x64__8wekyb3d8bbwe.Appx.zip](https://github.com/jellyfin/jellyfin-web/files/6356918/Microsoft.HEVCVideoExtension_1.0.31823.0_x64__8wekyb3d8bbwe.Appx.zip)

Nice, problem solved with [`HEVC Video Extensions from Device Manufacturer @1.0.31823`](https://www.free-codecs.com/hevc_video_extension_download.htm)

**Comment by riverscn** [comment]
the problem remains in version 90.0.818.62. please re-open this issue.

**Comment by nyanmisaka** [comment]
> Seems that Edge team have found the issue. The lastest HEVC plugin is incompatible with Edge. You can remove the existing plugin and downgrade it to 1.0.31823 for the time being. https://www.free-codecs.com/hevc_video_extension_download.htm
> 
> ![image](https://user-images.githubusercontent.com/14953024/106110559-d8c0f100-6185-11eb-8d09-83278cd69b76.png)

**This is not a jellyfin issue.** Please follow the solution above to downgrade your HEVC plugin.

**Comment by GooDeeJAY** [comment]
Still facing this issue after 4 years lmao

**Comment by anujsedhai** [comment]
Still facing this exact issue in Chrome
