### ISSUE TITLE
Playback starts even if not authorized

### ISSUE THREAD

**Issue by the-lazy-fox** [jellyfin/jellyfin-web#2268]
**Describe The Bug**
I have deactivated all forms of playback authorization for one user nevertheless, after the warning (contact your administrator) the player still opens on Safari/Firefox iOS.

It works fine in the 10.7.0 latest (nothing happening after the warning pop up) but not in the nightly as of today.

(I’m using the nightly version because turning off the playback is hiding the download feature in the latest...)

**Screenshots**
![1EA704AE-314B-4849-9AD5-BD2C35EAD128](https://user-images.githubusercontent.com/35723598/103171570-9b4b0a00-484d-11eb-8472-50dde881e48d.jpeg)

**System (please complete the following information):**
 - Platform: Linux Docker (linuxserver)
 - Browser: Safari
 - Jellyfin Version: 10.7.0

**Comment by EVOTk** [comment]
I have the same issue

System (please complete the following information):

    Platform: Linux Docker (linuxserver)
    Browser: Chrome 87.0.4280.88
    Jellyfin Version: 10.7.0 nightly

In Firefox 84.0.1 (64 bits), playback no start, as it should be, but the player is still displayed after the ban message.

**Comment by the-lazy-fox** [comment]
The issue is still happening

**Comment by thornbill** [comment]
@the-lazy-fox Can you confirm what version you are seeing this in? Is it working correctly in the latest stable release 10.7.5 and not working in unstable? Thanks!

**Comment by cvium** [comment]
Shouldn't this have been fixed by https://github.com/jellyfin/jellyfin-web/pull/2374?

**Comment by thornbill** [comment]
Sounds like it. I think we can close this then pending someone confirming it is still an issue.
