### ISSUE TITLE
[Issue]: Cover images blurry

### ISSUE THREAD

**Issue by Madpeterz** [jellyfin/jellyfin-web#3258]
### Please describe your bug

call to

```
.../items/<code>/Images/Primary?fillHeight=320&fillWidth=213&quality=96&tag=<tag>
```

can sometimes display a blurry cover image on first load.

the call also does not seem to support cache correctly so the UI can forget about it if you scroll away leading to blurry images 

the blurry images can also sometimes correct themselves on scrolling

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: RockyLinux (running docker) [so Debian?]
- Virtualization: Docker
- Clients:
Jellyfin Media Player - Windows
Crome - Windows 

- FFmpeg Version: Unsure [jellyfin:10.7.7 default]
- Playback Method: Unsure [jellyfin:10.7.7 default]
- Hardware Acceleration: None
- Plugins: Default
- Reverse Proxy: No
- Base URL: Internal IP address
- Networking: bridge
- Storage: local
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/57852827/147874635-b770a4c9-415e-4f64-85e5-8457d7793743.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ferferga** [comment]
This is intended, so you have placeholders while the image is being downloaded. Lots of sites do this, like medium.

What's exactly the problem? They don't disappear after the load finishes?

**Comment by Madpeterz** [comment]
they never load and stay blurry.

**Comment by ferferga** [comment]
@Madpeterz They become blurry on scroll because having 100+ images loaded on the screen at the same time is really taxing in resources, so we unload them until they come again into view. So 2 and 3 are expected.

Do you have any steps for reproduce 1? Can you provide a video?

**Comment by Madpeterz** [comment]
steps to reproduce
1: Scroll down. 50% of the time one line will not load for a long time if at all.



https://user-images.githubusercontent.com/57852827/147895286-0885d629-8e0c-4549-a500-942dda4a82d8.mp4


https://user-images.githubusercontent.com/57852827/147895309-d83e8662-47f4-4ca5-9cc7-945c95861610.mp4

**Comment by ferferga** [comment]
@Madpeterz Can you try building this branch and see if you can reproduce the issue there?:
https://github.com/jellyfin/jellyfin-web/pull/3144

**Comment by Madpeterz** [comment]
jellyfin/jellyfin-server
jellyfin/jellyfin-web
or
jellyfin/jellyfin


do not seem to have the tag 
f9ad84d or blurhash-worker

am I missing the tags for it?

**Comment by ferferga** [comment]
@Madpeterz No, you must build it manually, PRs are not in Docker, only commits to master.

You must clone this repo, checkout to the branch and build it by following our readme's instructions.

**Comment by Madpeterz** [comment]
Notes:
after deleting the cache folder and config folder - re-running the wizard

the issue continues in crome and firefox, 
Turning off Blurred placeholders just results in a gray box that does not seem to load.
[Jellyfin Web 10.7.6]

but I am currently unable to recreate it in the Desktop client 
[Jellyfin Media Player 1.6.1]

**Comment by Madpeterz** [comment]
After building the blurhash-worker version and force clearing chrome I am unable to recreate the issue (and imo the blur looks nicer and loads alot faster when scrolling)

**Comment by Madpeterz** [comment]
Clean install of windows 11 and Vivaldi and I am no longer able to recreate this issue, This might have been a flag set in chrome that was messing it up.

im going to close this issue for now and hope it never returns.

**Comment by mapeca** [comment]
I am also experiencing this issue with two friends of mine. Sometimes we have two or three rows blurred. We all use the Brave browser and Windows 10. Tried on Firefox 97.0.1 and does not happen, only in Chrome and Brave (did not try other chromium based, Tried Brave [1.36.109 Chromium: 99.0.4844.51] and Chrome 99.0.4844.51). Tell me if i could help in any way

![image](https://user-images.githubusercontent.com/32661062/156869053-04219a0a-9de7-4058-85bf-148b6f9493ad.png)
![image](https://user-images.githubusercontent.com/32661062/156869077-ecba7c9a-a874-4da9-b93f-4acfa9a56c15.png)

**Comment by thornbill** [comment]
What version of Jellyfin are you running @mapeca?

**Comment by mapeca** [comment]
> What version of Jellyfin are you running @mapeca?

10.7.7 Windows based

**Comment by thornbill** [comment]
The fix listed above is only available in unstable.

**Comment by mapeca** [comment]
> The fix listed above is only available in unstable.

oops, sorry :/ my bad. Thanks for your work guys

**Comment by 0x09AF** [comment]
I am running 10.8.3 in docker and started having blurry thumbnails everywhere.
It started happening after I added another external hard drive and re-deployed my container.
The blurry thumbnails are present even on the media that is stored on the main drive where Jellyfin resides with the original library. No clue what to do...
What was "the fix above"? Clean install? I tried re-deploying, restarting my container - didn't help...

**Comment by mapeca** [comment]
I also have an external hard drive

**Comment by aaemon** [comment]
Still facing this issue. It is the only major issue for me using jellyfin :(

**Comment by ferferga** [comment]
@aaemon In 10.8.6?

**Comment by aaemon** [comment]
just updated to 10.8.6, and the issue is solved... thanks :)

**Comment by HikariNoKitsune** [comment]
Not to bring up a probably dead thing... but this is still an issue. I just recently switched from Plex over to Jellyfin because of the seemingly MUCH more stable use of hardware encoding when in a docker container. However, almost none of the images load. I have only ever seen a small handful of cover images actually show up, while the rest remain blurry... and this is using the Jellyfin Media Player, locally on the network. It does the same via Chrome or Opera, or when using the Jellyfin Android App. 

I do not experience what the OP had: where they may be there, but once you scroll they disappear. Mine have just, never been there. 
![image](https://user-images.githubusercontent.com/10123174/211169182-720e5229-fa30-4d78-9f97-7723b089d408.png)
![image](https://user-images.githubusercontent.com/10123174/211169192-789e8616-8320-414e-bf2a-3a2c08419a43.png)
![image](https://user-images.githubusercontent.com/10123174/211169223-705ea6d0-71ee-48e0-83fd-a5b4dbcff659.png)
![image](https://user-images.githubusercontent.com/10123174/211169383-7aef0501-1ff4-458c-af8f-efbd58e5c962.png)
![image](https://user-images.githubusercontent.com/10123174/211169396-d7490b67-d98f-49cb-ad94-761defd116d6.png)


I understand the need/use of a placeholder image, but what I don't understand, is that these placeholder images appear to be just extremely low res version of the actual cover image... which means these had to be generated somehow, or loaded from somewhere. So if that is the case, why not just use the normal cover photos and ditch these 'low res but not really low res' images? With that, it also doesn't appear to actually download any images for the meta data either. as in, images for 'cast and crew' don't show up at all for a decent portion of things.

![image](https://user-images.githubusercontent.com/10123174/211169323-75928b73-45b8-422f-96a2-aa45c102474f.png)

I apologize if any of this comes off as rude/mean. I'm pretty bad at explaining things... but ultimately I currently have an entire library that is 80-90% 'blank/blurry' images which makes navigating an already kinda clunky UX a slow process as you need to stop and read everything instead of just go 'oh that's the cover for x movie!' and just click it. Just kind of a weird pill to swallow after having came from using Plex for over 5 years.

**Comment by vince6794** [comment]
I can confirm on version 10.8.9-1 this is still an issue:
![image](https://user-images.githubusercontent.com/31125013/216311563-9df632c0-560e-48cb-833b-bfed74502bed.png)

Randomly some covers can't load out of the blur.

Let me know how I can help further.
I could even investigate the code if someone could point me in the right direction.

**Comment by Madpeterz** [comment]
@vince6794 this issue awhile ago you will prob want to open a new issue otherwise it wont get seen prob.

**Comment by karlseven** [comment]
This still happens to me 10.8.9 using rclone and google drive, i have to click back and click the category again to load the images but not all are appearing specially if you have big collection which is weird since the files is just in my local NAS

**Comment by HikariNoKitsune** [comment]
As an update to mine:

I went 'fuck it' and went back to just using Plex... that lasted like... maybe a week, before just hating Plex all over again for constantly dropping the transcode streams repeatedly if the video is paused for longer than 30 seconds.. So, figured I'd give Jellyfin another shot. 

This time, instead of using a docker for Plex, I just installed a full blown Ubuntu 20 somethin VM and installed Jellyfin onto it. This basically basically fixed my loading images issue, and also the weird 'incorrectly detected shows' issue (had a weird one where about 80% of my videos and tv shows were just being reported as being Rick n Morty Anime... had to manually assign IMDB codes to everything... very annoying...) But after using a dedicated VM instead of a Docker, only about 20 shows detected as being Rick n Morty...

Heads up though for anyone who's wanting to just go 'screw it' like I did and try using a Vm... **MAKE SURE YOU ADD ALL THE PORTS JELLYFIN USES TO THE VM'S FIREWALL RULES!!! IF YOU DON'T, IT WILL FREAK THE HELL OUT LIKE HAVING A NUCLEAR MELTDOWN!**... Found that bit out as any time I'd try to stream a movie, it would just cause the webpage to either fully crash, go into an epileptic seizure, or play the first 2 seconds of whatever you're trying to watch, then start pausing, unpausing, pausing, unpausing, over and over and over... Once I added all the ports to be allowed on the Ubuntu Firewall, all that weirdness went away. :D

Now, if only we can get the Chromecast situation working better, this would be absolutely Golden. I'm utterly loving just how much faster Jellyfin is for transcoding media, AND the fact that it seems to transcode the ENTIRE MOVIE/SHOW, and not just 30 seconds of it... I think this is the problem with Plex which causes it to die if you have it paused longer than 30 seconds... it transcodes 30 seconds of video, then stops.. so if you pause, it never gets the signal to 'resume' the transcode and thus you are just left with a dead stream. So massive Kudos to Jellyfin for doing this in the way that I feel it should always be! 

Now, if it'd just keep that transcoded video that'd be cooler. As in, if its transcoded the video fully then it stores that transcode somewhere if you haven't 'finished' watching the video, yet had to close out of the video to go do something. This would be awesome because then when you come back to watch, it can just pick right back up where you left off without having to consume more power to re-transcode everything for a 2nd or 3rd time. Could be something like "if the video is stopped, continue transcoding but store somewhere. if after 24 hours the video isn't finished, then delete the transcoded video".

I know I'm just kinda rambling here and it isn't really the place for that sorta rambling.. just kinda my 2 cents and dreams lol..

**Comment by peterzolczer** [comment]
I have this very issue on my fresh install on docker, 10.8.10. Blurry or no (cover/artist/poster/etc.) images, doesn't matter whether I use a client or open it in browser:

![image](https://github.com/jellyfin/jellyfin-web/assets/121183484/200c415b-2e6f-4075-ba0c-64c137cf5a79)

**Comment by nitschis** [comment]
If you have Dark Reader extension installed, disable it for your Jellyfin.
