### ISSUE TITLE
User can delete item within collections, even if it is disabled in the servers profile settings

### ISSUE THREAD

**Issue by TotoCon** [jellyfin/jellyfin-web#3912]
**Describe The Bug**

User can delete item within collections, even if it is disabled in the servers profile settings

**Steps To Reproduce**

1. Disable media deletion in the servers profile settings
2. Enter collection library
3. Choose a collection
4. Click on "More"
5. Delete option is shown

**Expected Behavior**

If disabled in the servers profile settings, delete option should not be there.

**System (please complete the following information):**
 - Platform: Windows 7, Windows 10
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.8.4

**Additional Context**

This behavior is also in the Media Player 1.7.1
The option to delete is not visible in the AndroidTV app.

**Comment by KingIzzymon** [comment]
This is still a problem. Only the server admin should be able to add/remove items from collections

**Comment by Shadowghost** [comment]
Most likely already fixed in master by https://github.com/jellyfin/jellyfin/pull/8887 and https://github.com/jellyfin/jellyfin/pull/8526

**Comment by yunyuyuan** [comment]
@Shadowghost But it seems that this issue still exists.
![image](https://github.com/jellyfin/jellyfin-web/assets/45785585/9e60aab1-c254-4965-be81-acd9fde45b30)

## login with the `readonly` user:
![image](https://github.com/jellyfin/jellyfin-web/assets/45785585/1e8c10aa-39b6-4a32-9d26-8ff60b6a3e5b)

My jellyfin server:
```
Server: manjaro-docker-jellyfin

Version: 10.8.10

Operating System: Linux

Architecture: X64
```

**Comment by Shadowghost** [comment]
This functionality is only available in 10.9 server
