### ISSUE TITLE
Backdrops not cleaned up

### ISSUE THREAD

**Issue by TMUniversal** [jellyfin/jellyfin-web#3916]
**Describe The Bug**
Backdrop image containers are retained when rotating to the next image, even though only one is displayed at a time.
The old/unused `div`s are (apparently) not re-used.
This causes performance hiccups when waiting on the home page for a while, especially when having the tab open a for while in the background and then returning.

**Steps To Reproduce**

1. Go to User Preferences
2. Click on Display
3. Scroll down to Backdrops
4. Make sure backdrops are enabled
5. Return to home screen
6. Wait a few rotations of the backdrop images
7. See in `body > div.backdropContainer` (`/html/body/div[1]`) that there are multiple `div.backdropImage`, even though only one is displayed.

**Expected Behavior**
Clean up unused `div`s in `body > div.backdropContainer`.

**Logs**
not applicable

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows 10
 - Browser: Brave 1.43.93 Chromium: 105.0.5195.127
 - Jellyfin Version: 10.8.4

**Additional Context**

**Comment by TMUniversal** [comment]
This is still an issue.

**Comment by dmitrylyzo** [comment]
I am able to reproduce this way:
1. While on the home screen, wait for the backdrop to start transition.
There will be 2 divs.
2. Click on any movie (with a backdrop).
The second (previous) backdrop isn't removed.

This is probably because the removing occurs in the animation end handler, which isn't called when we forcibly change the backdrop.
https://github.com/jellyfin/jellyfin-web/blob/df54d013bcf19d1831a170dc60aba5397c53491a/src/components/backdrop/backdrop.js#L56-L58

**Comment by Kaysera** [comment]
I am not able to reproduce this issue, I think it has been addressed.

**Comment by TMUniversal** [comment]
> I am not able to reproduce this issue, I think it has been addressed.

I can still reproduce on Jellyfin Web `10.8.11`.
Note that you must have the Tab Jellyfin runs in deselected, so that another tab is shown in that window.

**Comment by Kaysera** [comment]
This is the behavior recorded on the current development version, Jellyfin Web `10.9.0`. Does this show the bug fixed, or am I not understanding it properly?

![output](https://github.com/jellyfin/jellyfin-web/assets/12697014/ab183b65-381b-40f8-9709-221a92888d10)

**Comment by pnivek** [comment]
I am also experiencing this issue. It really takes away from the awesome backdrops feature jellyfin has. Is there an update on the PR that contains the fix to these? https://github.com/jellyfin/jellyfin-web/pull/4826

**Comment by sic6SaNdMaN** [comment]
Would love to see this confirmed bug finally fixed.
Having problems with this since I started using Jellyfin nearly 5 years ago...

I don't want to keep Backdrops always disabled, because it looks awesome, when you view the details page of a Movie or TV show. I would love to finally be able to use this feature!
But it renders the startpage unusable, when you leave it open as a tab in your browser in the background.

When enough time has passed, the whole Web Interface is unusable and crippled:

<img width="1837" height="605" alt="Image" src="https://github.com/user-attachments/assets/f80bce14-e5f1-4465-8aae-3629d8df2a5a" />

<img width="1837" height="705" alt="Image" src="https://github.com/user-attachments/assets/7e349102-8d13-4d00-8c75-c86d7dc4c993" />

A forced reload with cache cleanup is the only way to get the tab up and running again.

So... one way would be to make the timeout for backdrop changing on the starting page configurable.
Another way would be to make them deactivateable for the starting page seperately, but leave them active for movies/TV shows.
The third way would be to fix the damn thing... especially, when there already was a PR back in 2023 that is still around.

Thanks.

**Comment by jagharskov** [comment]
<img width="646" height="658" alt="Image" src="https://github.com/user-attachments/assets/c146dea1-aa80-4121-8cbb-53fddcdc01c3" />

Very annoying bug. Using block element with ublock lets me see a ton of backdrop elements stacked on top of each other simply from having the webui running in another tab.
