### ISSUE TITLE
[Issue]: Sub title desync JF 10.8.9

### ISSUE THREAD

**Issue by MrToast99** [jellyfin/jellyfin-web#4346]
### Please describe your bug

Upgraded 10.8.8 > 10.8.9 and now subtitles desync or loop if you jump ahead in a file.

Steps:
Start a show with subs, 
Jump ahead a few mins 

This will cause the subs to loop the last 2 or 3 lines constantly.

Turning off subs and back on will resume the subs but they will be desync'd by 2-3 secs. This persists even if playback is stopped and started again.  

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows server 2016
- Virtualization: 
- Clients: browser
- Browser: Chrome
- FFmpeg Version:5.1.2
- Playback Method:
- Hardware Acceleration: no
- Plugins: playback reporting, reports
- Reverse Proxy: yes
- Base URL: /jellyfin
- Networking: NAT
- Storage:NFS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbeamond** [comment]
We've been looking into this at https://github.com/jellyfin/jellyfin/issues/8403. This issue here has some small differences, but it may help figure out some of the problems with the information found in that thread.

**Comment by MrToast99** [comment]
Updated to 10.8.10 and this longer seems to an issue... 

I'm guessing due to [jellyfin/jellyfin-web#4362 ](https://github.com/jellyfin/jellyfin-web/pull/4362)

**Comment by dmitrylyzo** [comment]
> I'm guessing due to [jellyfin/jellyfin-web#4362 ](https://github.com/jellyfin/jellyfin-web/pull/4362) or j[ellyfin/jellyfin-web#4385](https://github.com/jellyfin/jellyfin-web/pull/4385)

https://github.com/jellyfin/jellyfin-web/pull/4385

**Comment by AIndoria** [comment]
This remains an issue. Not stale.

**Comment by AIndoria** [comment]
> Please answer same questions: [#4346 (comment)](https://github.com/jellyfin/jellyfin-web/issues/4346#issuecomment-1426918112)
> + What player do you use on Android?

Android Says Web Player. On Android TV Both Exo and libVLC have the same issue (libVLC to a ...[lesser extent but it is there](https://github.com/jellyfin/jellyfin/issues/2547#issuecomment-1696827346)). Forcing the video to open in an external player such as MX tends to solve the issue almost completely _at times_.

**Comment by danielwikander** [comment]
Do we have any idea what could be causing this, or where in the codebase one could start looking? This issue is bothering me so much I might try looking into it myself, but I'm new to the project so any guidance here would be appreciated.

**Comment by Migs3** [comment]
Is this still being looked into?  This is one of the most annoying things "wrong" with jellyfin.  It doesn't seem like a difficult concept to simply use a single time value for displaying the video and subtitles. I don't know the underlying code or anything but it seems like the only way this could be a problem is if there are multiple time values that are needing to be kept in sync when there really should only be one time value when serving content.

Not only the above, but on a related note there should be a menu option in the gui/web to set a subtitle sync time value (+/-).  A simple method to time shift the subtitles ahead or behind slightly. Not only would that help negate some of the frustration of this issue, but some subtitles are just slightly off when you have different media/subtitle releases that don't quite match up.

**Comment by dmitrylyzo** [comment]
> Is this still being looked into? This is one of the most annoying things "wrong" with jellyfin. It doesn't seem like a difficult concept to simply use a single time value for displaying the video and subtitles. I don't know the underlying code or anything but it seems like the only way this could be a problem is if there are multiple time values that are needing to be kept in sync when there really should only be one time value when serving content.

The original issue has been fixed by https://github.com/jellyfin/jellyfin-web/pull/4385
If you have steps to reproduce your case, post them (what client, what subtitles type, etc.).
Maybe even open a new issue (it may be different from the original one).

> Not only the above, but on a related note there should be a menu option in the gui/web to set a subtitle sync time value (+/-). A simple method to time shift the subtitles ahead or behind slightly. Not only would that help negate some of the frustration of this issue, but some subtitles are just slightly off when you have different media/subtitle releases that don't quite match up.

It is in the Player Settings (gear button) / Subtitle Offset.

**Comment by Ellypax** [comment]
Hello, I'm experiencing ongoing issues with Jellyfin 10.8.13 running on Linux Docker x64. Specifically, I'm encountering varying subtitle offsets depending on the file. This problem persists across multiple files sourced from different origins. Each time, the subtitles fail to synchronize properly.

This issue occurs specifically with integrated subtitles when accessed via Jellyfin web interface. I've been primarily using Safari on MacOS 14.4 and iOS 17.4.1 for playback.

Interestingly, when I utilize Jellyfin for Android TV with libVLC, there are no subtitle synchronization issues. Additionally, downloading the file and playing it on my computer also does not reproduce the problem.

**Comment by Migs3** [comment]
> 
> The original issue has been fixed by #4385 If you have steps to reproduce your case, post them (what client, what subtitles type, etc.). Maybe even open a new issue (it may be different from the original one).
> 
> It is in the Player Settings (gear button) / Subtitle Offset.

Maybe this is specific to the Android TV client, It's mainly used on our Firestick at home and my GF insists on constantly bashing my "new media server" due to subtitles never being correct and that she always has to turn them off.

**Comment by cthulhuz** [comment]
Can confirm that this bug is present on Samsung TV (Tizen) running [jellyfin-web](https://github.com/jellyfin/jellyfin-web/tree/3cf66d4b9d22797675b473e8b03c2c270e69cd45). The subtitles work fine on other devices and players. Bug occurs when seeking in some files that are being direct played with SRT subtitles. Direct playing a file from the beginning works fine until you seek in it.

**Comment by joost00719** [comment]
> d players. Bug occurs when seeking in some files that are being direct played with SRT subtitles. Direct playing a file from the

Same here. VLC player also isn't a proper fix. It does fix the sync issues, but the content will be resized to fit the screen, and since almost no movie is 16:9, it will stretch almost all content. Also, it suffers from stutters and audio pops (chrome cast with android tv. version "jellfyin-androidtv 0.16.7 release").

**Comment by thornbill** [comment]
> AndroidTV doesn't use web, so that's a different story.

As Dmitry already pointed out, if you are having issues with the Android TV app this is not the correct place.

**Comment by viown** [comment]
Can confirm that this issue still exists in 10.9. Seems to most commonly happen when direct streaming.

**Comment by random-human-being** [comment]
I have also just experienced it in 10.9 with SRT subs, after skipping ahead. The video was being transcoded.

Switching to PGS subs forced them to be burned into the video, fixing the issue.

**Comment by SpyrosRoum** [comment]
I've started experiencing this on 10.9, while before (<10.9) it only happened on mobile clients, now it happens on the web too.  
Is there any possible workaround or anything? It's extremely annoying, especially since the only "fix" I have found is to download the video locally

**Comment by Kusefiru** [comment]
I am noticing similar behavior on jellyfin-web 10.9.2 with Firefox 126.0.
The subtitle synchronisation is correct at first, but get worst with time or when jumping in the file.

I have tested both embedded ASS subs and external SRT subs.

If I switch to Edge (125.0.2535.51), the subtitles are correctly synced. This is also the case when playing the video file directly on my computer, so I believe the subtitles in themselves are fine.

**Comment by fungos** [comment]
Same issue here with Roku client, LGTv client and FireTV client.

srt subtitles, some start correct and desync as it progress, most desync after a pause-quit-resume, some are just completely desync from start. It was ok with server 10.8.something, but 10.9 is becoming almost unusable unfortunately, forcing me back to Plex to be able to watch almost anything, which means the subtitles are perfect and the problem is with Jellyfin, not sure if entirely server side or both sides.

**Comment by SpyrosRoum** [comment]
Something I've noticed and helps a little is that using the https://github.com/jellyfin/jellyfin-vue web client seems to fix the issue for items that have de-synced on the main web client.
Unfortunately this is not a complete solution since the vue client still misses features, but it saves me from having to download anything that I was watching and is broken...

**Comment by deniax2** [comment]
Interestingly enough, for me using Swiftfin always has synced subtitles. Doesnt matter if i scrub throught the movie or change the language of the sub.

When I switch to my laptop with Chrome or Firefox, the subtitles are always desynced. I can sync them manually, but the moment I fast-forward or reverse, the subs are de-synced again.

So it really seems for me a client issue

**Comment by viown** [comment]
> Interestingly enough, for me using Swiftfin always has synced subtitles. Doesnt matter if i scrub throught the movie or change the language of the sub.
> 
> When I switch to my laptop with Chrome or Firefox, the subtitles are always desynced. I can sync them manually, but the moment I fast-forward or reverse, the subs are de-synced again.
> 
> So it really seems for me a client issue

This is because Swiftfin direct-plays nearly all types of media without issues, while Chrome and Firefox have a more limited codec support which in your case is leading to direct-streaming or transcoding (which is what causes this issue).

This issue is almost purely server-side because the server cannot deliver the exact timestamp the client is asking for. Instead, the server will seek back to the earliest keyframe (which can be anywhere from 5-8 seconds wide) causing the de-sync. 

Although I'm sure this could be fixed with some new API introductions where the server is able to tell the client the exact timestamp it's seeking to, but that requires explicit client support and there could be some other complications I'm missing. Maybe @gnattu could explain?

**Comment by SpyrosRoum** [comment]
@viown what you are saying is interesting but it raises the question, why did it become a bigger problem with v10.9? Something must have changed in the backend and perhaps it's possible to revert or fix that without breaking/client changes

**Comment by gnattu** [comment]
> why did it become a bigger problem with v10.9

it is not. This issue was created for 10.8 isn't it?

**Comment by SpyrosRoum** [comment]
The issue was created for 10.8, but it didn't happen for me (on firefox) until 10.9, and based on the activity on the issue I believe other experienced the same.

To be clear I had experienced it before on the mobile (android, default player), but never on firefox.

**Comment by creekdrops** [comment]
Not sure if this issue is related, but I've noticed that when accessing subtitles over HLS using Apple's native player in Mac and iOS, the subtitles are extremely delayed by about 12 seconds.

**Comment by finnurthorisson** [comment]
Also happening for me with 10.9.6 and 10.9.7 in Firefox but did not happen in 10.8.10

Transcoded (HEVC->H264) in browser is desynced but in app (Direct playing) it works like normal. I've also had it occasionally replay a short chunk in browser which usually triggers it to desync. Desync persists when leaving and resuming

**Comment by aykutcan** [comment]
I am having problems with embedded subtitles. (Various formats, Various Browsers).

When I seek while playing a video, the subtitle is desycing.

I am using Docker and No HW Acceleration (Do not judge me pls. I cant find any low bracket gpu yet)

```
Server version 10.9.8
Web version 10.9.8
Build version 10.9.8

```
Web Chrome: Broken
Web Firefox: Broken
Tizen Client : OK
Android TV Client: OK
Android Client : OK

I didn't try with DLNA (Because DLNA plugin is completely broken) but at this point it is obvious that it is a web client problem.

**Comment by Ali-Flt** [comment]
Disabling GPU acceleration in my chrome (Brave) settings fixed the issue for me.

**Comment by zdraganov** [comment]
Same issue here. Only being able to fix by turning always on the subscription burning. Tested on web Chrome.

**Comment by KillsT3aler69** [comment]
Currently experiencing this issue on server version 10.10.3

**Comment by pablobass** [comment]
> Currently experiencing this issue on server version 10.10.3

Same versión as you.

For me, the only workaround that worked is enabling subtitle burning to "all".
But that's done on the client-side, on each one and on each app. Plus, you lose the ability to customize font, size, color, etc.
...and besides, the server has to re-encode in all cases.
Hopefully, they can resolve this issue soon. It's not minor one.

**Comment by KillsT3aler69** [comment]
> > Currently experiencing this issue on server version 10.10.3
> 
> Same versión as you.
> 
> For me, the only workaround that worked is enabling subtitle burning to "all". But that's done on the client-side, on each one and on each app. Plus, you lose the ability to customize font, size, color, etc. ...and besides, the server has to re-encode in all cases. Hopefully, they can resolve this issue soon. It's not a minor one.
> 
> At least it would be good to have the option to do this on the server-side until they can resolve the issue.

Unfortunately, there is no option (to the best of my knowledge) to burn in the subtitles on Anroid TV, which is my main platform to watch jellyfin.

**Comment by pablobass** [comment]
> Unfortunately, there is no option (to the best of my knowledge) to burn in the subtitles on Anroid TV, which is my main platform to watch jellyfin.

That's right, I had forgotten about that when I wrote the post. I know it's a personal issue, but my mother needs to enlarge the font size of the subtitles to be able to see them... and this way she can't use it directly... and she's one of the people I care most about being able to use it.

**Comment by shogeki** [comment]
I've been running into this issue with latest Jellyfin.  

For me, this occurs after moving the scrubber, when using the web client in Firefox only.  

When I loaded the web client in Chromium I could jump ahead and back in the media without the subtitles desyncing.  

I tried different subtitle settings but it did not appear to make a difference with regards to the sync issue.  I did notice that the various settings (size, shadow) were not working in Firefox either.

**Comment by ericswpark** [comment]
This issue persists on 10.10.6, on the official mobile Jellyfin apps. Tested on an iPad Pro and S24 Ultra. If the playback is started from the beginning then the subtitles are in sync, but if I try and scrub to a specific point on the timeline or resume playback then the subtitle will get desynced, interestingly faster than the dialogue (so the subtitles spoil the dialogue which is very annoying).

This issue doesn't appear on the desktop Jellyfin Media Player client (Windows), probably because it's a wrapper around mpv.

**Comment by Elaws** [comment]
Still happening. Are there any ETA for a fix please ? This quite serious bug was reported two years ago, and it makes the app basicallly unusable for people relying on subtitles to watch a movie.

Thank you very much.

**Comment by fungos** [comment]
I don't believe this will ever be fixed, which is really sad, so I would suggest you to tune way down your hope.

**Comment by pablobass** [comment]
They don't rely on subtitles for 90% of movies or more.
It's really sad. If it were an audio sync issue, I assure you they would have fixed it in less than a week.
For them, we're a very small percentage of users who use and need subtitles, evidently.

**Comment by Elaws** [comment]
I just wish the team were as prompt in investigating this two-year-old unresolved bug as they are in tagging and deleting our polite follow-up messages as 'off-topic'.

**Comment by z411** [comment]
I can't believe this is still an issue. Better to just stick to Plex if you want to retain any kind of mental sanity at this point.

**Comment by dnno** [comment]
I think I only experience this problem with embedded subtitles in mkv files. If they are located alongside a movie file as an srt, syncing works. Haven't done extensive testing, though.

**Comment by z411** [comment]
I tried with Firefox and Chromium, both embedded ASS subtitles in mkv and external SRT subtitles; they all get badly desynced after seeking anywhere. Running 2025063005 nightly.

It just seems like a client-side problem with the soft subtitle rendering of the web player specifically, so browsers and any clients that load the web player are affected. Clients that use their own player (ie. mpv) aren't affected because they render the subtitles themselves.

The issue has persisted for me ever since I started using JF (a year ago) so I wouldn't know when this got introduced.

**Comment by pablobass** [comment]
> I tried with Firefox and Chromium, both embedded ASS subtitles in mkv and external SRT subtitles; they all get badly desynced after seeking anywhere. Running 2025063005 nightly.
> 
> It just seems like a client-side problem with the soft subtitle rendering of the web player specifically, so browsers and any clients that load the web player are affected. Clients that use their own player (ie. mkv) aren't affected because they render the subtitles themselves.
> 
> The issue has persisted for me ever since I started using JF (a year ago) so I wouldn't know when this got introduced.

To me, it happens also in the AndroidTV app.

**Comment by z411** [comment]
> To me, it happens also in the AndroidTV app.

I thought the Android/Android TV apps were kind of wrappers for the web client, is it not? In that case there must be some shared code in-between that's causing it...

**Comment by pablobass** [comment]
> > To me, it happens also in the AndroidTV app.
> 
> I thought the Android/Android TV apps were kind of wrappers for the web client, is it not? In that case there must be some shared code in-between that's causing it...

The Android one, yes, but I thought not the Android TV one. But I'm not sure. It must be, maybe they both use Android's "WebView Framework".

**Comment by frankhuurman** [comment]
Still an issue on the most recent Brave browser.
Subtitles are perfectly in sync when playing the video locally in VLC but through jellyfin they're out of sync sometimes even from the start of the episode.

**Comment by Ifiht** [comment]
Confirming still an issue with both the Android TV player and when played on Firefox browser, latest Jellyfin `10.10.7`, happens 100% of the time when skipping/seeking on foreign audio with English subtitles.

**Comment by KimPig** [comment]
Is there no solution? I recently worked on integrating ASS files within mkv,mp4 files, and I found this error. I am only experiencing this problem with ASS files inside mkv, mp4. I remember there was no problem with the existing external SRT files.

Turning on the option to burn the ASS subtitles in the settings will fix this, but I don't want to transcode the H264 file. Third-party Android apps like Findroid will caption properly.

**Comment by noncrab** [comment]
I'm reasonably sure i've seen this with 10.11.2, too.

**Comment by CryptoCopter** [comment]
Still a problem on `10.11.5` - also happens when I close the play and then resume watching later.

**Comment by brunoorsolon** [comment]
Just a +1 I guess, it's very random for me.
But MOSTLY for embedded subtitles, when it's a separate file it usually works better for longer periods.

**Comment by fungos** [comment]
issue still affecting different clients.

**Comment by alaestor** [comment]
The desktop app has been pretty borked for me so I switched to chromium and I've been experiencing this issue quite consistently; they're about a second early for me if I seek anywhere or rejoin etc. Maybe related to transcoding? I can confirm it seems to be ASS subtitles (I've only tested embedded)

Still no progress on this, eh?
