### ISSUE TITLE
Issue with Chrome-based browsers and the 

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin-web#4371]
**Describe The Bug**
On Chrome-based browsers, if you have the setting "Use hardware acceleration when available" enabled (in the browser's settings), videos played through Jellyfin will not properly buffer. Apart from that, depending on your system, you can also get an issue where transcoding a video to have subtitles hardcoded into the video will cause video/audio/sub sync issues when you skip to any part of the video.

Turning off the hardware acceleration option in the browser settings fixes the video playback issues with Jellyfin, but causes system performance issues since everything is being sent to the CPU instead.

This Chrome video playback issue happens when HWA is both enabled or disabled in Jellyfin's dashboard.

**Steps To Reproduce**
1. On any Chrome-based browser, make sure hardware acceleration is enabled in its settings.
2. Start Jellyfin and play any video.
3. Notice how no video buffering is happening on the playback bar despite playback info reporting otherwise.

**Expected Behavior**
Chrome should properly playback video and allow proper video buffering to occur when browser hardware acceleration is enabled.

**System (please complete the following information):**
 - Platform: Windows 10 & 11
 - Browser: Chrome
 - Jellyfin Version: 10.8.9

**Additional Context**
Firefox doesn't have these issues.
I have Jellyfin running in a docker container.

**Comment by Schaka** [comment]
Just wanted to pop in here saying I can confirm this issue. I'm also seeing an issue where some videos (HVEC, 4k HDR 10 bit) are not re-encoded in HVEC despite Chrome (110) supporting it. I end up with h264 80bbit streams. I suspect this is related.

Turning off hardware acceleration taxes the CPU to no end but resolves the issue described in the OP. Transcoding is still done to h264.

**Comment by Matix-Media** [comment]
I can confirm, I have a similar issue.

**Comment by lorivaro** [comment]
Confirmed, and just to add, the reason Firefox works flawlessly is because it doesn't support HEVC at all and instead gets served transcoded H254 video. 
In this case the transcoding load lies in the server and not the client cpu/gpu which explains the minimal client-side load.

**Comment by mwdiers** [comment]
I have this issue with AV1 (10-bit) files on Chrome, with 5.1+ audio. Stereo tracks are fine. If I do something to force transcoding, such as enable subtitles, or drop the bitrate below the raw file, then audio sync is fine on all audio tracks.

Firefox supports AV1 natively and has no sync issues with or without transcoding.

**Comment by kennychan-git** [comment]
can confirm this as well in accordance to all others, issue with chrome hardware acceleration. i took a look at the logs after trying to play the hevc video in chrome vs firefox. when i played the video on chrome, it just shows the title/banner/picture and nothing is playing. on firefox it is playing as usual.

**from chrome Version 111.0.5563.147 (Official Build) (64-bit)** 
```
[INF] User policy for "redacted". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[INF] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="redacted.mp4", AudioStreamIndex=1, SubtitleStreamIndex=-1 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/24851ece-d3aa-efc0-cc4a-93c94012b5e8/stream.mp4?MediaSourceId=24851eced3aaefc0cc4a93c94012b5e8&Static=true&VideoCodec=hevc&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&SubtitleMethod=Encode&Tag=d204d97a5ac1260d0504ca79d6a2e310"
```

**from firefox 111.0.1 (64-bit**
```
[INF] User policy for "redacted". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[INF] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="redacted.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported ) "media:/videos/24851ece-d3aa-efc0-cc4a-93c94012b5e8/master.m3u8?MediaSourceId=24851eced3aaefc0cc4a93c94012b5e8&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=322692923&AudioBitrate=384000&AudioSampleRate=48000&MaxFramerate=23.976025&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d204d97a5ac1260d0504ca79d6a2e310&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=6&aac-profile=lc&h264-profile=high,main,baseline,constrainedbaseline&h264-rangetype=SDR&h264-level=52&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported"
```

**Comment by maru801** [comment]
This is fixed now after a few updates to chrome-based browsers. Closing this issue due to that.

**Comment by Red-Eyed** [comment]
> This is fixed now after a few updates to chrome-based browsers. Closing this issue due to that.

I still have this problem. 
In which version the fix has landed?

Thanks

**Comment by guemi** [comment]
Same here. Issue with recent Jellyfin 10.9.9 running in Docker. 

I've disabled Hardware Acceleration i Firefox, but still issue persists on x265 files.
