### ISSUE TITLE
Pagination missing on Grouped Libraries

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin-web#4574]
**Describe The Bug**
There is no Pagination populated on grouped Libraries main view.

**Steps To Reproduce**
1. Populate two Libraries with 20 Movies
2. Set the Library Page Size to 10 for that user
3. Create a new Groupe Library in Settings -> Home -> Library Folders "Automatically group content from the following folders into views such as 'Movies', 'Music' and 'TV'" (Example Movies)
4. Go to the main page
5. Open that new Library (Movies)
6. Scroll to the bottom

Pagination element is missing.

**Expected Behavior**
A pagination element to move to the next page when there are more items to load then the current page shows.

**Screenshots**
![image](https://user-images.githubusercontent.com/6794763/236584857-5cb25873-c63a-4098-a303-7c5a522346b6.png)

**System (please complete the following information):**
 - Platform: Docker Official
 - Browser: Edge Version 112.0.1722.68 (Official build) (64-bit)
 - Jellyfin Version: 10.8.10

**Comment by Killface1980** [comment]
I'm facinng a similar, more general issue here.
With the switch to the unstable branch, all my library items show only the amount per page with the pagination missing.
Nothing unusual in the logs. Switching back to the stable branch solves the issue for me.
Also JF on iOs truncates the entries to the max display value per page.
Issue appeared on JF in Docker and with the Windows installation.
Using the unstable web client with the stable server result in no issue. 

![image](https://github.com/jellyfin/jellyfin-web/assets/16738568/f4de0da8-6a45-4b3d-9d9a-0ee3b9c5d0d4)

**Comment by Killface1980** [comment]
Should be fixed soonish https://github.com/jellyfin/jellyfin/pull/9818

**Comment by Bond-009** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/9818

**Comment by Jurrer** [comment]
I am still experiencing this issue in docker image `10.8.12`, x64

**Comment by thornbill** [comment]
The fix likely was not backported to the 10.8 release branch.

**Comment by Jurrer** [comment]
I see, can it be backported to the next release?
Is there a process to do it?

**Comment by JackTorrance1** [comment]
Hi, I started having this problem in 10.9.2. I combined views for multiple movie libraries but I am missing pagination.
