### ISSUE TITLE
Regional ratings missing in Parental Controls

### ISSUE THREAD

**Issue by IzaacJ** [jellyfin/jellyfin-web#4694]
**Describe The Bug**
Parental Control is missing regional ratings when configuring maximum allowed rating for a user.

**Steps To Reproduce**

1. Have a movie with a rating such as SE-11 or other regional ratings.
2. Try to set the maximum allowed rating for a user to SE-11

**Expected Behavior**

Be able to use the regional ratings when restricting content for a child.

**Logs**

**Screenshots**

![image](https://github.com/jellyfin/jellyfin-web/assets/711323/6bc53efd-7414-4851-adb8-7e0b77f11f38)
![image](https://github.com/jellyfin/jellyfin-web/assets/711323/a075616e-037b-4ba5-aa1a-cc14e8930ee3)

**System (please complete the following information):**
 - Platform: Windows 11
 - Browser: Edge 114.1823.51
 - Jellyfin Version: 10.8.10

**Additional Context**

**Comment by Shadowghost** [comment]
Already (partially) fixed in master by https://github.com/jellyfin/jellyfin/pull/8526

The main problem is that the shown rating levels are decided by what UI language you have.

**Comment by IzaacJ** [comment]
Oh, missed that one when I searched. I suspect that I still get incorrect rating options with Swedish UI language since that isn't included in 10.8.10, or did I get it wrong?

**Comment by Shadowghost** [comment]
Correct, this is only in master and will not be backported to 10.8.x
