### ISSUE TITLE
No Way To Login After Removing Device Using Devices Section Of Dashboard

### ISSUE THREAD

**Issue by MovieWiz** [jellyfin/jellyfin-web#5626]
**Describe The Bug**
Browser opens on home page containing just the Jellyfin banner.  No way to proceed.

**Steps To Reproduce**
1) On server PC, click "Open Jellyfin" on the windows tray icon.  Ensure you're logged in and close the browser.  My browser was Firefox.
2) Login with another browser and access the Devices section of the dashboard.  Remove the device from (1) or remove all devices.
3) 1) On server PC, click "Open Jellyfin" on the windows tray icon.  

**Expected Behavior**
It should always be possible to login to the server.

**Logs**

**Screenshots**
![Jelly](https://github.com/jellyfin/jellyfin-web/assets/83739410/b92b0a03-deba-4044-82b0-2077185c626d)

**System (please complete the following information):**
 - Windows
 - Browser:  Firefox  (also with Chrome and Edge)
 - Jellyfin Version: [e.g. 10.9.3]

**Additional Context**
Only way to correct the problem is to clear the cache of the browser.  So this suggests that certain elements of the homepage are allowed to be cached that should not be.

Same behaviour with Jellyfin Media Player after its device is removed from the dashboard.  Only way to fix the problem was to remove the "cache" folder of the "Jellyfin Media Player" appdata folder.

Also had this happen on the tizen app.  With no obvious way to clear the cache, I was forced to uninstall and reinstall the app.

I don't think that's it's relevant but my UserID on the Jellyfin server has no password -- I'm the only user on a Jellyfin server that is only accessible on my local lan.

**Comment by hunxjunedo** [comment]
requesting assignment, if open to external contributions.

**Comment by thornbill** [comment]
We don't assign issues typically. Anyone is welcome to work on any issue. That said, this specific issue should be fixed by https://github.com/jellyfin/jellyfin/pull/11873.

**Comment by MovieWiz** [comment]
One thing I want to make clear is that I only needed to clear cache in the browser to fix the problem.  I did not clear the cookies.  So the invalid login token was still present.  The presence of the invalid token reacts differently after clearing the cache -- i.e. the redirect to the login page happens.  So it really sounds to me like there are elements of the home page that allowed to be cached that should not.

**Comment by MovieWiz** [comment]
After installing the 10.9.4 update, the problem appears to be fixed.  Thank you to all that helped make this happen.

I tested the following to cases:

1) Firefox (after token was invalidated using another browser)

2) Jellyfin Media Player 1.10.1 (with "Force External Web Client" enabled so that Jellyfin-web 10.94 is used rather than the embedded 10.9.2 client).  So, presumably, JMP will be fixed once it is rebuilt to have 10.9.4 as its embedded client.

So I am assuming that all clients based on Jellyfin-web will be fixed now -- although some might need to be rebuilt first.

**Comment by MovieWiz** [comment]
Looks like I made a mistake. The fix must have been on the server side and the embedded 10.9.2 JMP client no longer has the login problem.
