### ISSUE TITLE
Default cast device feature not working

### ISSUE THREAD

**Issue by hugues999** [jellyfin/jellyfin-web#6000]
**Describe The Bug**

The `Set as default` option for cast devices has not been working since 10.9.9 (and 10.9.10). It is lost any time we reload the web app or restart any Jellyfin client.

A similar bug was opened for this and was closed as fixed for 10.9.10 but it didn't seem to fix it: https://github.com/jellyfin/jellyfin-web/issues/5878.

**Steps To Reproduce**

1. Open the web application in a browser
2. Click the cast button
3. Select a cast device, for example MPV-Shim
4. Click on the cast device, check "Set as default"
5. Reload the page
6. The cast device is unselected, back to local playback

**Expected Behavior**

Normally, up to 10.9.8, selecting "Set as default" for a cast device meant that this device would automatically be connected when opening the client.

**Logs**

**Screenshots**

<img width="241" alt="image" src="https://github.com/user-attachments/assets/6a07fb7b-4399-4060-ade0-39ab05f837f6">

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.9.10

**Additional Context**

These steps can also be reproduced on any Jellyfin client, I have the same problem in the Windows desktop client and in the Android phone app. They would all select the default cast device previously before 10.9.9.

Thank you!

**Comment by viown** [comment]
This does seem to work as expected when running in development mode locally but not on the current production version and I'm still not quite sure why.

**Comment by thornbill** [comment]
Are there any relevant messages in the browser console?

**Comment by viown** [comment]
The interesting console messages I found which I can't find in development are:

> web socket closed
> nulling out web socket
...
> web socket opened

**Comment by kraM1tt** [comment]
Also having the same issue on latest builds

**Comment by thornbill** [comment]
I'm hoping this will be fixed by #6013, but I also added a bunch of logging to help us track it further if the issue continues. We will just have to see when the next release happens.

**Comment by viown** [comment]
It does not seem like this issue is fixed in 10.9.11, it looks like the websocket open event never gets called according to the logs.

**Comment by viown** [comment]
> ![image](https://private-user-images.githubusercontent.com/59093760/374400338-649b08c0-c247-423b-af28-d2f697c0449f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzUzMDYsIm5iZiI6MTcyODM3NTAwNiwicGF0aCI6Ii81OTA5Mzc2MC8zNzQ0MDAzMzgtNjQ5YjA4YzAtYzI0Ny00MjNiLWFmMjgtZDJmNjk3YzA0NDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA4MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNWYxYTFkN2RjODljMjUwYTliYTMzYjZiZGNjNDMxYWRhYjFjM2FlNDdkNDVhMmU2YTc0Yzc1MWRhNDJhMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gmINuKL2-JMNN3lQa6YAY1BRi2gkJW3lgsUTq-xQKQI) This issue is not fixed. If I reload the page, the cast device is unselected, back to local playback

This is fixed in the latest unstable, you'll get it by 10.10.

**Comment by OlegAckbar** [comment]
I still have this issue but only when accessing Jellyfin Web through Apache.
Here's my Apache config: https://pastebin.com/Le3ZXryE
I configured jellyfin-mpv-shim to domain "jellyfin.server.home"
