### ISSUE TITLE
Swiping on the Book Player does not navigate the pages of the Book

### ISSUE THREAD

**Issue by XeClutch** [jellyfin/jellyfin-web#6160]
**Describe The Bug**

The swipe controls meant to allow users to swipe left/right through pages on the Book Player (`src/plugins/bookPlayer`), are not working. Leaving users no way to navigate through pages of their content.

**Steps To Reproduce**
Note: Reproduction requires the server to have a book library and for the viewer to be on a mobile device.
1. Go to Books
2. Select an individual Book
3. Hit the Play button
4. Swipe left and/or right

**Expected Behavior**

When viewing a Book in the Book Player, swiping should navigate through the content pages.

**Screenshots**

![Untitled](https://github.com/user-attachments/assets/21cccebd-b30f-4992-9cb4-2ebc633322e4)

**System**
 - Platform: Android
 - Browser: Jellyfin App (Chromium)
 - Jellyfin Version: 10.9.9

**Comment by viown** [comment]
Since you're on 10.9.9, this bug was fixed here in 10.9.10 https://github.com/jellyfin/jellyfin-web/pull/5843

Could you please update and see if it fixes your issue?

**Comment by XeClutch** [comment]
@viown Just updated and it actually is working now if I'm explicitly using a browser but still broken in the android app. My understanding was that app was basically just an embedded browser but maybe not?

**Comment by viown** [comment]
Hmm, I'm not sure about the android app, but perhaps it's caching some pages? Can you try re-installing? I just did a quick test on the android app and it seems to work fine.

**Comment by thornbill** [comment]
Closing since this should be fixed. Feel free to reopen or comment if you experience the issue again.
