### ISSUE TITLE
Firefox: cannot play AV1 encoded media

### ISSUE THREAD

**Issue by SvetlinZarev** [jellyfin/jellyfin-web#7430]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-web/issues?q=is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

I've transcoded some of my media files to AV1. Now I'm no longer able to play them on Firefox (tested on Mac & Linux). The files play fine under Chrome or the Android app (using VLC).

The symptoms are exactly the same as in https://github.com/jellyfin/jellyfin-web/issues/5364 which was reported (and closed) more than a year ago. 

The only line that appears in the logs is this:
```
[2025-12-15 17:23:54.013 +02:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "svetlin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
```

No FFmpeg log file is created.

### Reproduction Steps

1. Use Firefox (tested with 145.0.1) on linux/mac (I don't use windows, so I do not know if the issue is reproducible there)
2. Try to play the attached AV1 encoded media:

[output.mkv.zip](https://github.com/user-attachments/files/24170120/output.mkv.zip)

### Actual behaviour:

Nothing happens. The player tries to "load" for forever.

### Expected behavior:

The media is played sucessfully.

### Media info of the file

```shell
ffprobe version 8.0.1 Copyright (c) 2007-2025 the FFmpeg developers
  built with Apple clang version 17.0.0 (clang-1700.4.4.1)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/8.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      60.  8.100 / 60.  8.100
  libavcodec     62. 11.100 / 62. 11.100
  libavformat    62.  3.100 / 62.  3.100
  libavdevice    62.  1.100 / 62.  1.100
  libavfilter    11.  4.100 / 11.  4.100
  libswscale      9.  1.100 /  9.  1.100
  libswresample   6.  1.100 /  6.  1.100
Input #0, matroska,webm, from 'output.mkv':
  Metadata:
    title           : Star Trek - The Next Generation - S01E02 - The naked now
    ENCODER         : Lavf61.7.100
  Duration: 00:00:09.22, start: 0.000000, bitrate: 1034 kb/s
  Chapters:
    Chapter #0:0: start 0.007000, end 7.000000
      Metadata:
        title           : 00:00:00.000
  Stream #0:0: Video: av1 (libdav1d) (Main), yuv420p(tv, bt709), 1440x1080, SAR 1:1 DAR 4:3, 23.98 fps, 23.98 tbr, 1k tbn, start 0.007000 (default)
    Metadata:
      BPS             : 1360723
      NUMBER_OF_FRAMES: 65555
      NUMBER_OF_BYTES : 465059725
      _STATISTICS_WRITING_APP: mkvmerge v96.0 ('It's My Life') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2025-12-14 12:27:31
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:00:07.013000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, 5.1, fltp (default)
    Metadata:
      title           : Opus 5.1 @ 256kbs
      BPS             : 222277
      NUMBER_OF_FRAMES: 136723
      NUMBER_OF_BYTES : 75975909
      _STATISTICS_WRITING_APP: mkvmerge v96.0 ('It's My Life') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2025-12-14 12:27:31
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:00:07.008000000
  Stream #0:2(eng): Subtitle: subrip (srt)
    Metadata:
      BPS             : 65
      NUMBER_OF_FRAMES: 635
      NUMBER_OF_BYTES : 22477
      _STATISTICS_WRITING_APP: mkvmerge v96.0 ('It's My Life') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2025-12-14 12:27:31
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:00:09.223000000
```

### Logs

```
[2025-12-15 17:23:54.013 +02:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "svetlin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
```

### FFmpeg logs

```shell
None. No ffmpeg logs are created
```

### Server version

10.11.5

### Web version

10.11.5

### Build version

10.11.5

### Platform

Linux, Mac

### Browser

Firefox 145.0.1

### Additional information

<img width="1643" height="915" alt="Image" src="https://github.com/user-attachments/assets/daced9a6-81ab-47dc-85b7-3ab6051f8fba" />

**Comment by nyanmisaka** [comment]
```
Video
ID                             : 1
Format                         : AV1
Format/Info                    : AOMedia Video 1
Format profile                 : Main@L4.0
Codec ID                       : V_AV1
Duration                       : 7 s 13 ms
Bit rate                       : 1 361 kb/s
Width                          : 1 440 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 4:3
Frame rate mode                : Variable
Frame rate                     : 9 347.640 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0 (Type 0)
Bit depth                      : 8 bits
Bits/(Pixel*Frame)             : 0.000
Stream size                    : 444 MiB
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709
```

`9347.640 FPS` is not a valid frame rate. Therefore, Firefox rejected it. You need to fix the file or report this issue to Firefox.

**Comment by SvetlinZarev** [comment]
@nyanmisaka Hi, thank you for looking into my issue.

How did you get that value for the framerate ? From the `ffprobe` output I can see `23.98 fps`:

```
  Stream #0:0: Video: av1 (libdav1d) (Main), yuv420p(tv, bt709), 1440x1080, SAR 1:1 DAR 4:3, 23.98 fps, 23.98 tbr, 1k tbn, start 0.007000 (default)
```

Also jellyfin reports the correct 23.9 fps: 

<img width="1175" height="674" alt="Image" src="https://github.com/user-attachments/assets/f3d04fd0-1fb3-449f-96a5-4bfef568188f" />

Also the video is encoded with constant frame rate, not variable frame rate.

**Comment by nyanmisaka** [comment]
https://github.com/MediaArea/MediaInfo

Both the MKV container and the AV1 bitstream contain a frame rate value, but FFmpeg tends to read it from the video bitstream. Apparently, Firefox prefers to read it from the container.

**Comment by SvetlinZarev** [comment]
Thanks. Here is the `mediainfo` output from the original file, not the attached sample:

```
mediainfo Star\ Trek\ -\ The\ Next\ Generation\ -\ S01E01\ -\ Encounter\ At\ Farpoint.mkv Star\ Trek\ -\ The\ Next\ Generation\ -\ S01E01\ -\ Encounter\ At\ Farpoint.mkv
General
Unique ID                                : 41910459664156107974597258155294918303 (0x1F87A93261DF9BA09172CD4040E7069F)
Complete name                            : Star Trek - The Next Generation - S01E01 - Encounter At Farpoint.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 794 MiB
Duration                                 : 1 h 31 min
Overall bit rate                         : 1 214 kb/s
Frame rate                               : 23.976 FPS
Title                                    : Star Trek - The Next Generation - S01E01 - Encounter At Farpoint
Encoded date                             : 2025-12-14 12:27:46 UTC
Writing application                      : mkvmerge 96.0 ('It's My Life') 64-bit
Writing library                          : libebml v1.4.5 + libmatroska v1.7.1

Video
ID                                       : 1
Format                                   : AV1
Format/Info                              : AOMedia Video 1
Format profile                           : Main@L4.0
Codec ID                                 : V_AV1
Duration                                 : 1 h 31 min
Bit rate                                 : 978 kb/s
Width                                    : 1 440 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 0)
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.026
Stream size                              : 639 MiB (81%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 1 h 31 min
Bit rate                                 : 234 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C Lb Rb LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 50.000 FPS (960 SPF)
Bit depth                                : 32 bits
Compression mode                         : Lossy
Stream size                              : 153 MiB (19%)
Title                                    : Opus 5.1 @ 256kbs
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 31 min
Bit rate                                 : 66 b/s
Frame rate                               : 0.221 FPS
Count of elements                        : 1206
Stream size                              : 44.5 KiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : 00:00:00.000
00:01:45.355                             : 00:01:45.105
00:07:06.343                             : 00:07:06.092
00:14:35.917                             : 00:14:35.625
00:27:29.398                             : 00:27:29.273
00:36:01.284                             : 00:36:01.076
00:47:09.744                             : 00:47:09.535
00:57:02.836                             : 00:57:02.794
01:06:20.226                             : 01:06:20.018
01:11:42.590                             : 01:11:42.548
01:18:24.241                             : 01:18:24.158
01:30:17.579                             : 01:30:17.245

General
Unique ID                                : 41910459664156107974597258155294918303 (0x1F87A93261DF9BA09172CD4040E7069F)
Complete name                            : Star Trek - The Next Generation - S01E01 - Encounter At Farpoint.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 794 MiB
Duration                                 : 1 h 31 min
Overall bit rate                         : 1 214 kb/s
Frame rate                               : 23.976 FPS
Title                                    : Star Trek - The Next Generation - S01E01 - Encounter At Farpoint
Encoded date                             : 2025-12-14 12:27:46 UTC
Writing application                      : mkvmerge 96.0 ('It's My Life') 64-bit
Writing library                          : libebml v1.4.5 + libmatroska v1.7.1

Video
ID                                       : 1
Format                                   : AV1
Format/Info                              : AOMedia Video 1
Format profile                           : Main@L4.0
Codec ID                                 : V_AV1
Duration                                 : 1 h 31 min
Bit rate                                 : 978 kb/s
Width                                    : 1 440 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 0)
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.026
Stream size                              : 639 MiB (81%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 1 h 31 min
Bit rate                                 : 234 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C Lb Rb LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 50.000 FPS (960 SPF)
Bit depth                                : 32 bits
Compression mode                         : Lossy
Stream size                              : 153 MiB (19%)
Title                                    : Opus 5.1 @ 256kbs
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 31 min
Bit rate                                 : 66 b/s
Frame rate                               : 0.221 FPS
Count of elements                        : 1206
Stream size                              : 44.5 KiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : 00:00:00.000
00:01:45.355                             : 00:01:45.105
00:07:06.343                             : 00:07:06.092
00:14:35.917                             : 00:14:35.625
00:27:29.398                             : 00:27:29.273
00:36:01.284                             : 00:36:01.076
00:47:09.744                             : 00:47:09.535
00:57:02.836                             : 00:57:02.794
01:06:20.226                             : 01:06:20.018
01:11:42.590                             : 01:11:42.548
01:18:24.241                             : 01:18:24.158
01:30:17.579                             : 01:30:17.245

```

And here is the the `ffprobe` output for the same file:
```
 ffprobe Star\ Trek\ -\ The\ Next\ Generation\ -\ S01E01\ -\ Encounter\ At\ Farpoint.mkv 
ffprobe version 7.1.3-1 Copyright (c) 2007-2025 the FFmpeg developers
  built with gcc 15 (Debian 15.2.0-9)
  configuration: --prefix=/usr --extra-version=1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-libmfx --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, matroska,webm, from 'Star Trek - The Next Generation - S01E01 - Encounter At Farpoint.mkv':
  Metadata:
    title           : Star Trek - The Next Generation - S01E01 - Encounter At Farpoint
    encoder         : libebml v1.4.5 + libmatroska v1.7.1
    creation_time   : 2025-12-14T12:27:46.000000Z
  Duration: 01:31:22.89, start: -0.007000, bitrate: 1214 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 105.355000
      Metadata:
        title           : 00:00:00.000
    Chapter #0:1: start 105.355000, end 426.343000
      Metadata:
        title           : 00:01:45.105
    Chapter #0:2: start 426.343000, end 875.917000
      Metadata:
        title           : 00:07:06.092
    Chapter #0:3: start 875.917000, end 1649.398000
      Metadata:
        title           : 00:14:35.625
    Chapter #0:4: start 1649.398000, end 2161.284000
      Metadata:
        title           : 00:27:29.273
    Chapter #0:5: start 2161.284000, end 2829.744000
      Metadata:
        title           : 00:36:01.076
    Chapter #0:6: start 2829.744000, end 3422.836000
      Metadata:
        title           : 00:47:09.535
    Chapter #0:7: start 3422.836000, end 3980.226000
      Metadata:
        title           : 00:57:02.794
    Chapter #0:8: start 3980.226000, end 4302.590000
      Metadata:
        title           : 01:06:20.018
    Chapter #0:9: start 4302.590000, end 4704.241000
      Metadata:
        title           : 01:11:42.548
    Chapter #0:10: start 4704.241000, end 5417.579000
      Metadata:
        title           : 01:18:24.158
    Chapter #0:11: start 5417.579000, end 5482.644000
      Metadata:
        title           : 01:30:17.245
  Stream #0:0: Video: av1 (libdav1d) (Main), yuv420p(tv, bt709), 1440x1080, SAR 1:1 DAR 4:3, 23.98 fps, 23.98 tbr, 1k tbn (default)
      Metadata:
        BPS             : 977762
        DURATION        : 01:31:22.644000000
        NUMBER_OF_FRAMES: 131452
        NUMBER_OF_BYTES : 670090335
        _STATISTICS_WRITING_APP: mkvmerge v96.0 ('It's My Life') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2025-12-14 12:27:46
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: opus, 48000 Hz, 5.1, fltp (default)
      Metadata:
        title           : Opus 5.1 @ 256kbs
        BPS             : 234348
        DURATION        : 01:31:22.866000000
        NUMBER_OF_FRAMES: 274144
        NUMBER_OF_BYTES : 160612495
        _STATISTICS_WRITING_APP: mkvmerge v96.0 ('It's My Life') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2025-12-14 12:27:46
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip (srt)
      Metadata:
        BPS             : 66
        DURATION        : 01:31:04.875000000
        NUMBER_OF_FRAMES: 1206
        NUMBER_OF_BYTES : 45567
        _STATISTICS_WRITING_APP: mkvmerge v96.0 ('It's My Life') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2025-12-14 12:27:46
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

The attached sample video was cut like that:
```
ffmpeg -i Star\ Trek\ -\ The\ Next\ Generation\ -\ S01E01\ -\ Encounter\ At\ Farpoint.mkv -t 7 -c copy output.mkv 
```

and maybe that resulted in the wrong FPS & framerate mode value. 

The issue with the playback is present also with the original file, and the FPS value is correct there.

**Comment by nyanmisaka** [comment]
<img width="163" height="112" alt="Image" src="https://github.com/user-attachments/assets/4669d16f-1ada-480a-84ca-120aa1fab80c" />

You can try dragging the video into Firefox. If it shows that the video cannot be played, it might be due to a bug in the MKV support that Firefox recently added.

Remuxing the file to MP4 using ffmpeg also allows Firefox to play it for me.

**Comment by SvetlinZarev** [comment]
Thanks. Indeed it might be a FF issue. Removing the subtitles and remuxing to webm worked in FF. But it failed to play the original file.

Shouldn't in that case jellyfin remux the video instead of trying to do a "direct play"?

**Comment by nyanmisaka** [comment]
I remember that FF's native MKV support was disabled not too long ago. https://github.com/jellyfin/jellyfin-web/pull/7335 So I'm not sure why you're still able to use direct play. @gnattu The fix doesn't seem to be working.

**Comment by gnattu** [comment]
Firefox has a weird behavior that mkv with av1+opus is treated as webm and will attempt to direct play. 

We disabled such behavior for audio not long ago:
https://github.com/jellyfin/jellyfin/pull/13345

**Comment by AeroBliss** [comment]
I am experiencing this issue. Please do not close it as stale.

**Comment by theguymadmax** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/15807

**Comment by darkbroodzed** [comment]
It is not fixed. Firefox still fail to play av1 with same "black screen and no logs"

**Comment by AeroBliss** [comment]
> It is not fixed. Firefox still fail to play av1 with same "black screen and no logs"

Did you try updating the Jellyfin server? They only now published the fix in this weeks Jellyfin release. @darkbroodzed 

For me the issue is resolved and I can play AV1 videos in Firefox and the mobile app now.

**Comment by darkbroodzed** [comment]
> Did you try updating the Jellyfin server? They only now published the fix in this weeks Jellyfin release.

It's last available right now:
Server version 10.11.6
Web version 10.11.6
Build version 10.11.6

**Comment by AeroBliss** [comment]
> > Did you try updating the Jellyfin server? They only now published the fix in this weeks Jellyfin release.
> 
> It's last available right now:
> Server version 10.11.6
> Web version 10.11.6
> Build version 10.11.6

Does the video play in the Jellyfin Desktop app?

**Comment by nyanmisaka** [comment]
The metadata of the affected files needs to be refreshed manually.

**Comment by darkbroodzed** [comment]
> Does the video play in the Jellyfin Desktop app?

Have no idea newer use desktop app, but it works in any chrome based browser.

> The metadata of the affected files needs to be refreshed manually.

Thank you. Manual metadata refresh for affected files fix issue.

I suspect it affect a lot of people, but they are not aware of this issue, i assume that auto triggered metadata update for av1 metadata on Jellyfin update is a bad idea, but maybe there is a other way to "autofix it" for users?

**Comment by nyanmisaka** [comment]
Alternatively, affected users can wait for the next "Scan Media Library" scheduled task.

**Comment by NotTimTam** [comment]
Bizarrely for me, on the initial load of an AV1 in firefox, I get the infinite spinning loader of death, and a failed to decode error. Also if I drag the file directly into firefox, it can't play it, (says its corrupted)

But if I simply refresh the browser and hit play, it triggers a request for a transcoded version and it starts playing the now h264 transcoded version. If there was a way to force jellyfin to transcode all AV1s into h264s, preferably specifically on firefox, that would probably fix this for me.
